### ISSUE TITLE
Mehr perks

### ISSUE THREAD

**Issue by Papadoubulus** [Fludixx/WoolBattle#1]
Tauscher und so ein item das man  bauen kann also wenn man das aktiviert wird 7 blocke vor dir gespawnt :D Danke Das Sie das machen﻿

**Comment by Gtafgu** [comment]
Finde Ich auch :D

**Comment by Aromastoffe** [comment]
:+1:

**Comment by Fludixx** [comment]
Jo Tauscher habe ich gemacht (siehe Version 1.1) dieses Bau Item finde ich Unnötig

**Comment by Papadoubulus** [comment]
Es wurde Ganz Cool sein wenn man mit pfeil wolle trifft das die kapput geht

**Comment by Fludixx** [comment]
@Papadoubulus Mal schauen, sollte nicht schwer sein das zu machen

**Comment by Fludixx** [comment]
@Papadoubulus Unnddd.. fertig! Version 1.1.2

**Comment by Ggander** [comment]
@Fludixx  es wurde cool sein  mit den Pfeil wenn man die wool trifft das die kapput geht

**Comment by Papadoubulus** [comment]
@Fludixx  Danke

**Comment by Gtafgu** [comment]
@Fludixx  Ist Es Möglich Das Man Wenn Man Mit Bogen Schießt Das Wolle Kostet?

**Comment by Aromastoffe** [comment]
**_ @Gtafgu_ Und dass wenn man auf wolle schießt dass sie verschwindet?**

**Comment by Fludixx** [comment]
@Gtafgu Klar geht das
@Aromastoffe Das hab ich schin implementiert (v.1,1,2)

**Comment by Gtafgu** [comment]
Kannst du es hinzufügen? @Fludixx

**Comment by Fludixx** [comment]
@Gtafgu Wie viel solls den kosten?

**Comment by Papadoubulus** [comment]
5
