### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by yPublicyFun** [Fludixx/WoolBattle#13]
Error: "Call to a member function setAutoSave() on null" (EXCEPTION) in "WoolBattle_dev-3(2).phar/src/Fludixx/WoolBattle/Main" at line 115 [17:34:24] [Server thread/DEBUG]: #0 src/pocketmine/plugin/PluginBase(111): Fludixx\WoolBattle\Main->onEnable() [17:34:24] [Server thread/DEBUG]: #1 src/pocketmine/plugin/PluginManager(613): pocketmine\plugin\PluginBase->setEnabled(boolean 1) [17:34:24] [Server thread/DEBUG]: #2 src/pocketmine/Server(1937): pocketmine\plugin\PluginManager->enablePlugin(Fludixx\WoolBattle\Main object) [17:34:24] [Server thread/DEBUG]: #3 src/pocketmine/Server(1923): pocketmine\Server->enablePlugin(Fludixx\WoolBattle\Main object) [17:34:24] [Server thread/DEBUG]: #4 src/pocketmine/Server(1717): pocketmine\Server->enablePlugins(integer 1) [17:34:24] [Server thread/DEBUG]: #5 src/pocketmine/PocketMine(243): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /home/gs/gs/data/servers/10398834/, string /home/gs/gs/data/servers/10398834/plugins/) [17:34:24] [Server thread/DEBUG]: #6 /home/gs/gs/data/servers/10398834/PocketMine-MP.phar(1): require(string phar:///home/gs/gs/data/servers/10398834/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

**Comment by yPublicyFun** [comment]
And one 1 too,can You do With joinsign and If anyone Join He geht the shop?

**Comment by yPublicyFun** [comment]
Get

**Comment by Gtafgu** [comment]
VannilaEnchant?

**Comment by yPublicyFun** [comment]
What

**Comment by yPublicyFun** [comment]
Ahh yea,nono i think it is what With the match

**Comment by Fludixx** [comment]
it's not finding the world (lobby, woolbattle1, woolbattle2.etc.)

**Comment by yPublicyFun** [comment]
Okay thanks
