### ISSUE TITLE
Woolbattle schützplatform bug 

### ISSUE THREAD

**Issue by Papadoubulus** [Fludixx/WoolBattle#2]

**Comment by Papadoubulus** [comment]
also manchmal geht sie aber manchmal bug man durch den block irgenwie

**Comment by Fludixx** [comment]
das liegt an dem ping vom server oder des users, man könnte es so machen das die plattform weiter unten spawnt, werde ich auch machen. man kann dann den abstand in der config /cloud/cfg/perks.yml einstellen werde ich noch hinzufügen

**Comment by Fludixx** [comment]
So gemacht! siehe Version 1.1.1

**Comment by Papadoubulus** [comment]
Danke echt Nett
