### ISSUE TITLE
Bug Da Steht seid Neuester Version Nicht mehr Wie viel leben man hat

### ISSUE THREAD

**Issue by Gtafgu** [Fludixx/WoolBattle#6]

**Comment by Fludixx** [comment]
Erkläre.
Ich habe in der neusten version ein Neues Level System gecodet, warscheinlich liegt es daran, hast du Logs oder kannst beschreiben wann das problem aufgetretten ist?

**Comment by Gtafgu** [comment]
Es Geht Alles tp aber Da steht keine leben

**Comment by Gtafgu** [comment]
Wenn Ich 10 mal sterbe werde ich züruck Tp wie normal aber da steht halt nix mehr
